<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'title' => "Afghanistan"),
            array('id' => 2,'code' => 'AL' ,'title' => "Albania"),
            array('id' => 3,'code' => 'DZ' ,'title' => "Algeria"),
            array('id' => 4,'code' => 'AS' ,'title' => "American Samoa"),
            array('id' => 5,'code' => 'AD' ,'title' => "Andorra"),
            array('id' => 6,'code' => 'AO' ,'title' => "Angola"),
            array('id' => 7,'code' => 'AI' ,'title' => "Anguilla"),
            array('id' => 8,'code' => 'AQ' ,'title' => "Antarctica"),
            array('id' => 9,'code' => 'AG' ,'title' => "Antigua And Barbuda"),
            array('id' => 10,'code' => 'AR','title' => "Argentina"),
            array('id' => 11,'code' => 'AM','title' => "Armenia"),
            array('id' => 12,'code' => 'AW','title' => "Aruba"),
            array('id' => 13,'code' => 'AU','title' => "Australia"),
            array('id' => 14,'code' => 'AT','title' => "Austria"),
            array('id' => 15,'code' => 'AZ','title' => "Azerbaijan"),
            array('id' => 16,'code' => 'BS','title' => "Bahamas The"),
            array('id' => 17,'code' => 'BH','title' => "Bahrain"),
            array('id' => 18,'code' => 'BD','title' => "Bangladesh"),
            array('id' => 19,'code' => 'BB','title' => "Barbados"),
            array('id' => 20,'code' => 'BY','title' => "Belarus"),
            array('id' => 21,'code' => 'BE','title' => "Belgium"),
            array('id' => 22,'code' => 'BZ','title' => "Belize"),
            array('id' => 23,'code' => 'BJ','title' => "Benin"),
            array('id' => 24,'code' => 'BM','title' => "Bermuda"),
            array('id' => 25,'code' => 'BT','title' => "Bhutan"),
            array('id' => 26,'code' => 'BO','title' => "Bolivia"),
            array('id' => 27,'code' => 'BA','title' => "Bosnia and Herzegovina"),
            array('id' => 28,'code' => 'BW','title' => "Botswana"),
            array('id' => 29,'code' => 'BV','title' => "Bouvet Island"),
            array('id' => 30,'code' => 'BR','title' => "Brazil"),
            array('id' => 31,'code' => 'IO','title' => "British Indian Ocean Territory"),
            array('id' => 32,'code' => 'BN','title' => "Brunei"),
            array('id' => 33,'code' => 'BG','title' => "Bulgaria"),
            array('id' => 34,'code' => 'BF','title' => "Burkina Faso"),
            array('id' => 35,'code' => 'BI','title' => "Burundi"),
            array('id' => 36,'code' => 'KH','title' => "Cambodia"),
            array('id' => 37,'code' => 'CM','title' => "Cameroon"),
            array('id' => 38,'code' => 'CA','title' => "Canada"),
            array('id' => 39,'code' => 'CV','title' => "Cape Verde"),
            array('id' => 40,'code' => 'KY','title' => "Cayman Islands"),
            array('id' => 41,'code' => 'CF','title' => "Central African Republic"),
            array('id' => 42,'code' => 'TD','title' => "Chad"),
            array('id' => 43,'code' => 'CL','title' => "Chile"),
            array('id' => 44,'code' => 'CN','title' => "China"),
            array('id' => 45,'code' => 'CX','title' => "Christmas Island"),
            array('id' => 46,'code' => 'CC','title' => "Cocos (Keeling) Islands"),
            array('id' => 47,'code' => 'CO','title' => "Colombia"),
            array('id' => 48,'code' => 'KM','title' => "Comoros"),
            array('id' => 49,'code' => 'CG','title' => "Congo"),
            array('id' => 50,'code' => 'CD','title' => "Congo The Democratic Republic Of The"),
            array('id' => 51,'code' => 'CK','title' => "Cook Islands"),
            array('id' => 52,'code' => 'CR','title' => "Costa Rica"),
            array('id' => 53,'code' => 'CI','title' => "Cote D Ivoire (Ivory Coast)"),
            array('id' => 54,'code' => 'HR','title' => "Croatia (Hrvatska)"),
            array('id' => 55,'code' => 'CU','title' => "Cuba"),
            array('id' => 56,'code' => 'CY','title' => "Cyprus"),
            array('id' => 57,'code' => 'CZ','title' => "Czech Republic"),
            array('id' => 58,'code' => 'DK','title' => "Denmark"),
            array('id' => 59,'code' => 'DJ','title' => "Djibouti"),
            array('id' => 60,'code' => 'DM','title' => "Dominica"),
            array('id' => 61,'code' => 'DO','title' => "Dominican Republic"),
            array('id' => 62,'code' => 'TP','title' => "East Timor"),
            array('id' => 63,'code' => 'EC','title' => "Ecuador"),
            array('id' => 64,'code' => 'EG','title' => "Egypt"),
            array('id' => 65,'code' => 'SV','title' => "El Salvador"),
            array('id' => 66,'code' => 'GQ','title' => "Equatorial Guinea"),
            array('id' => 67,'code' => 'ER','title' => "Eritrea"),
            array('id' => 68,'code' => 'EE','title' => "Estonia"),
            array('id' => 69,'code' => 'ET','title' => "Ethiopia"),
            array('id' => 70,'code' => 'XA','title' => "External Territories of Australia"),
            array('id' => 71,'code' => 'FK','title' => "Falkland Islands"),
            array('id' => 72,'code' => 'FO','title' => "Faroe Islands"),
            array('id' => 73,'code' => 'FJ','title' => "Fiji Islands"),
            array('id' => 74,'code' => 'FI','title' => "Finland"),
            array('id' => 75,'code' => 'FR','title' => "France"),
            array('id' => 76,'code' => 'GF','title' => "French Guiana"),
            array('id' => 77,'code' => 'PF','title' => "French Polynesia"),
            array('id' => 78,'code' => 'TF','title' => "French Southern Territories"),
            array('id' => 79,'code' => 'GA','title' => "Gabon"),
            array('id' => 80,'code' => 'GM','title' => "Gambia The"),
            array('id' => 81,'code' => 'GE','title' => "Georgia"),
            array('id' => 82,'code' => 'DE','title' => "Germany"),
            array('id' => 83,'code' => 'GH','title' => "Ghana"),
            array('id' => 84,'code' => 'GI','title' => "Gibraltar"),
            array('id' => 85,'code' => 'GR','title' => "Greece"),
            array('id' => 86,'code' => 'GL','title' => "Greenland"),
            array('id' => 87,'code' => 'GD','title' => "Grenada"),
            array('id' => 88,'code' => 'GP','title' => "Guadeloupe"),
            array('id' => 89,'code' => 'GU','title' => "Guam"),
            array('id' => 90,'code' => 'GT','title' => "Guatemala"),
            array('id' => 91,'code' => 'XU','title' => "Guernsey and Alderney"),
            array('id' => 92,'code' => 'GN','title' => "Guinea"),
            array('id' => 93,'code' => 'GW','title' => "Guinea-Bissau"),
            array('id' => 94,'code' => 'GY','title' => "Guyana"),
            array('id' => 95,'code' => 'HT','title' => "Haiti"),
            array('id' => 96,'code' => 'HM','title' => "Heard and McDonald Islands"),
            array('id' => 97,'code' => 'HN','title' => "Honduras"),
            array('id' => 98,'code' => 'HK','title' => "Hong Kong S.A.R."),
            array('id' => 99,'code' => 'HU','title' => "Hungary"),
            array('id' => 100,'code' => 'IS','title' => "Iceland"),
            array('id' => 101,'code' => 'IN','title' => "India"),
            array('id' => 102,'code' => 'ID','title' => "Indonesia"),
            array('id' => 103,'code' => 'IR','title' => "Iran"),
            array('id' => 104,'code' => 'IQ','title' => "Iraq"),
            array('id' => 105,'code' => 'IE','title' => "Ireland"),
            array('id' => 106,'code' => 'IL','title' => "Israel"),
            array('id' => 107,'code' => 'IT','title' => "Italy"),
            array('id' => 108,'code' => 'JM','title' => "Jamaica"),
            array('id' => 109,'code' => 'JP','title' => "Japan"),
            array('id' => 110,'code' => 'XJ','title' => "Jersey"),
            array('id' => 111,'code' => 'JO','title' => "Jordan"),
            array('id' => 112,'code' => 'KZ','title' => "Kazakhstan"),
            array('id' => 113,'code' => 'KE','title' => "Kenya"),
            array('id' => 114,'code' => 'KI','title' => "Kiribati"),
            array('id' => 115,'code' => 'KP','title' => "Korea North"),
            array('id' => 116,'code' => 'KR','title' => "Korea South"),
            array('id' => 117,'code' => 'KW','title' => "Kuwait"),
            array('id' => 118,'code' => 'KG','title' => "Kyrgyzstan"),
            array('id' => 119,'code' => 'LA','title' => "Laos"),
            array('id' => 120,'code' => 'LV','title' => "Latvia"),
            array('id' => 121,'code' => 'LB','title' => "Lebanon"),
            array('id' => 122,'code' => 'LS','title' => "Lesotho"),
            array('id' => 123,'code' => 'LR','title' => "Liberia"),
            array('id' => 124,'code' => 'LY','title' => "Libya"),
            array('id' => 125,'code' => 'LI','title' => "Liechtenstein"),
            array('id' => 126,'code' => 'LT','title' => "Lithuania"),
            array('id' => 127,'code' => 'LU','title' => "Luxembourg"),
            array('id' => 128,'code' => 'MO','title' => "Macau S.A.R."),
            array('id' => 129,'code' => 'MK','title' => "Macedonia"),
            array('id' => 130,'code' => 'MG','title' => "Madagascar"),
            array('id' => 131,'code' => 'MW','title' => "Malawi"),
            array('id' => 132,'code' => 'MY','title' => "Malaysia"),
            array('id' => 133,'code' => 'MV','title' => "Maldives"),
            array('id' => 134,'code' => 'ML','title' => "Mali"),
            array('id' => 135,'code' => 'MT','title' => "Malta"),
            array('id' => 136,'code' => 'XM','title' => "Man (Isle of)"),
            array('id' => 137,'code' => 'MH','title' => "Marshall Islands"),
            array('id' => 138,'code' => 'MQ','title' => "Martinique"),
            array('id' => 139,'code' => 'MR','title' => "Mauritania"),
            array('id' => 140,'code' => 'MU','title' => "Mauritius"),
            array('id' => 141,'code' => 'YT','title' => "Mayotte"),
            array('id' => 142,'code' => 'MX','title' => "Mexico"),
            array('id' => 143,'code' => 'FM','title' => "Micronesia"),
            array('id' => 144,'code' => 'MD','title' => "Moldova"),
            array('id' => 145,'code' => 'MC','title' => "Monaco"),
            array('id' => 146,'code' => 'MN','title' => "Mongolia"),
            array('id' => 147,'code' => 'MS','title' => "Montserrat"),
            array('id' => 148,'code' => 'MA','title' => "Morocco"),
            array('id' => 149,'code' => 'MZ','title' => "Mozambique"),
            array('id' => 150,'code' => 'MM','title' => "Myanmar"),
            array('id' => 151,'code' => 'NA','title' => "Namibia"),
            array('id' => 152,'code' => 'NR','title' => "Nauru"),
            array('id' => 153,'code' => 'NP','title' => "Nepal"),
            array('id' => 154,'code' => 'AN','title' => "Netherlands Antilles"),
            array('id' => 155,'code' => 'NL','title' => "Netherlands The"),
            array('id' => 156,'code' => 'NC','title' => "New Caledonia"),
            array('id' => 157,'code' => 'NZ','title' => "New Zealand"),
            array('id' => 158,'code' => 'NI','title' => "Nicaragua"),
            array('id' => 159,'code' => 'NE','title' => "Niger"),
            array('id' => 160,'code' => 'NG','title' => "Nigeria"),
            array('id' => 161,'code' => 'NU','title' => "Niue"),
            array('id' => 162,'code' => 'NF','title' => "Norfolk Island"),
            array('id' => 163,'code' => 'MP','title' => "Northern Mariana Islands"),
            array('id' => 164,'code' => 'NO','title' => "Norway"),
            array('id' => 165,'code' => 'OM','title' => "Oman"),
            array('id' => 166,'code' => 'PK','title' => "Pakistan"),
            array('id' => 167,'code' => 'PW','title' => "Palau"),
            array('id' => 168,'code' => 'PS','title' => "Palestinian Territory Occupied"),
            array('id' => 169,'code' => 'PA','title' => "Panama"),
            array('id' => 170,'code' => 'PG','title' => "Papua new Guinea"),
            array('id' => 171,'code' => 'PY','title' => "Paraguay"),
            array('id' => 172,'code' => 'PE','title' => "Peru"),
            array('id' => 173,'code' => 'PH','title' => "Philippines"),
            array('id' => 174,'code' => 'PN','title' => "Pitcairn Island"),
            array('id' => 175,'code' => 'PL','title' => "Poland"),
            array('id' => 176,'code' => 'PT','title' => "Portugal"),
            array('id' => 177,'code' => 'PR','title' => "Puerto Rico"),
            array('id' => 178,'code' => 'QA','title' => "Qatar"),
            array('id' => 179,'code' => 'RE','title' => "Reunion"),
            array('id' => 180,'code' => 'RO','title' => "Romania"),
            array('id' => 181,'code' => 'RU','title' => "Russia"),
            array('id' => 182,'code' => 'RW','title' => "Rwanda"),
            array('id' => 183,'code' => 'SH','title' => "Saint Helena"),
            array('id' => 184,'code' => 'KN','title' => "Saint Kitts And Nevis"),
            array('id' => 185,'code' => 'LC','title' => "Saint Lucia"),
            array('id' => 186,'code' => 'PM','title' => "Saint Pierre and Miquelon"),
            array('id' => 187,'code' => 'VC','title' => "Saint Vincent And The Grenadines"),
            array('id' => 188,'code' => 'WS','title' => "Samoa"),
            array('id' => 189,'code' => 'SM','title' => "San Marino"),
            array('id' => 190,'code' => 'ST','title' => "Sao Tome and Principe"),
            array('id' => 191,'code' => 'SA','title' => "Saudi Arabia"),
            array('id' => 192,'code' => 'SN','title' => "Senegal"),
            array('id' => 193,'code' => 'RS','title' => "Serbia"),
            array('id' => 194,'code' => 'SC','title' => "Seychelles"),
            array('id' => 195,'code' => 'SL','title' => "Sierra Leone"),
            array('id' => 196,'code' => 'SG','title' => "Singapore"),
            array('id' => 197,'code' => 'SK','title' => "Slovakia"),
            array('id' => 198,'code' => 'SI','title' => "Slovenia"),
            array('id' => 199,'code' => 'XG','title' => "Smaller Territories of the UK"),
            array('id' => 200,'code' => 'SB','title' => "Solomon Islands"),
            array('id' => 201,'code' => 'SO','title' => "Somalia"),
            array('id' => 202,'code' => 'ZA','title' => "South Africa"),
            array('id' => 203,'code' => 'GS','title' => "South Georgia"),
            array('id' => 204,'code' => 'SS','title' => "South Sudan"),
            array('id' => 205,'code' => 'ES','title' => "Spain"),
            array('id' => 206,'code' => 'LK','title' => "Sri Lanka"),
            array('id' => 207,'code' => 'SD','title' => "Sudan"),
            array('id' => 208,'code' => 'SR','title' => "Suriname"),
            array('id' => 209,'code' => 'SJ','title' => "Svalbard And Jan Mayen Islands"),
            array('id' => 210,'code' => 'SZ','title' => "Swaziland"),
            array('id' => 211,'code' => 'SE','title' => "Sweden"),
            array('id' => 212,'code' => 'CH','title' => "Switzerland"),
            array('id' => 213,'code' => 'SY','title' => "Syria"),
            array('id' => 214,'code' => 'TW','title' => "Taiwan"),
            array('id' => 215,'code' => 'TJ','title' => "Tajikistan"),
            array('id' => 216,'code' => 'TZ','title' => "Tanzania"),
            array('id' => 217,'code' => 'TH','title' => "Thailand"),
            array('id' => 218,'code' => 'TG','title' => "Togo"),
            array('id' => 219,'code' => 'TK','title' => "Tokelau"),
            array('id' => 220,'code' => 'TO','title' => "Tonga"),
            array('id' => 221,'code' => 'TT','title' => "Trinidad And Tobago"),
            array('id' => 222,'code' => 'TN','title' => "Tunisia"),
            array('id' => 223,'code' => 'TR','title' => "Turkey"),
            array('id' => 224,'code' => 'TM','title' => "Turkmenistan"),
            array('id' => 225,'code' => 'TC','title' => "Turks And Caicos Islands"),
            array('id' => 226,'code' => 'TV','title' => "Tuvalu"),
            array('id' => 227,'code' => 'UG','title' => "Uganda"),
            array('id' => 228,'code' => 'UA','title' => "Ukraine"),
            array('id' => 229,'code' => 'AE','title' => "United Arab Emirates"),
            array('id' => 230,'code' => 'GB','title' => "United Kingdom"),
            array('id' => 231,'code' => 'US','title' => "United States"),
            array('id' => 232,'code' => 'UM','title' => "United States Minor Outlying Islands"),
            array('id' => 233,'code' => 'UY','title' => "Uruguay"),
            array('id' => 234,'code' => 'UZ','title' => "Uzbekistan"),
            array('id' => 235,'code' => 'VU','title' => "Vanuatu"),
            array('id' => 236,'code' => 'VA','title' => "Vatican City State (Holy See)"),
            array('id' => 237,'code' => 'VE','title' => "Venezuela"),
            array('id' => 238,'code' => 'VN','title' => "Vietnam"),
            array('id' => 239,'code' => 'VG','title' => "Virgin Islands (British)"),
            array('id' => 240,'code' => 'VI','title' => "Virgin Islands (US)"),
            array('id' => 241,'code' => 'WF','title' => "Wallis And Futuna Islands"),
            array('id' => 242,'code' => 'EH','title' => "Western Sahara"),
            array('id' => 243,'code' => 'YE','title' => "Yemen"),
            array('id' => 244,'code' => 'YU','title' => "Yugoslavia"),
            array('id' => 245,'code' => 'ZM','title' => "Zambia"),
            array('id' => 246,'code' => 'ZW','title' => "Zimbabwe"),
            );
            DB::table('countries')->insert($countries);
    }
}
