<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CurrencyCodeMaster;

class CurrencyCodeMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['code' => 'USD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AFN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ARS', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AWG', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AUD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'AZN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BSD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BBD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BYR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EUR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BZD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BMD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BOB', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BAM', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BWP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BGN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BRL', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GBP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'BND', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KHR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CAD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KYD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CLP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CNY', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'COP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CRC', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HRK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CUP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CZK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DKK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'DOP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'XCD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'EGP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SVC', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FKP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'FJD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GHC', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GIP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GTQ', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GGP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'GYD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HNL', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HKD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'HUF', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ISK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'INR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IDR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IRR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'IMP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ILS', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JMD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JPY', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'JEP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KZT', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KPW', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KRW', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'KGS', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LAK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LVL', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LBP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LRD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'CHF', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LTL', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MKD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MYR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MUR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MXN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MNT', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'MZN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NAD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NPR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ANG', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NZD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NIO', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NGN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'NOK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'OMR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PKR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PAB', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PYG', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PEN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PHP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'PLN', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'QAR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RON', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RUB', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SHP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SAR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'RSD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SCR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SGD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SBD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SOS', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ZAR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'LKR', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SEK', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SRD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'SYP', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TWD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'THB', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TTD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRY', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TRL', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'TVD', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'UAH', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'UYU', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'UZS', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VEF', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'VND', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'YER', 'created_at' => now(), 'updated_at' => now()],
            ['code' => 'ZWD', 'created_at' => now(), 'updated_at' => now()],
        ];

        CurrencyCodeMaster::insert($data);
    }
}
